<?php
/**
 * @file
 * Install, update and uninstall functions for the purencool base installation profile.
 */

/**
 * Implements hook_install()
 */
function purencool_base_install() {
	// Can add code in here to make nodes, terms, etc.
  \Drupal::configFactory()
    ->getEditable('system.bootstrap')
		->set ('default', 'base')
->save();

  \Drupal::configFactory()
    ->getEditable('system.theme')
    ->set('admin', 'seven')
    ->save();
}
