<?php
/**
 * @file
 * Install, update and uninstall functions for the purencool installation profile.
 */

/**
 * Implements hook_install()
 */
function purencool_install() {
  // Can add code in here to make nodes, terms, etc.
  \Drupal::configFactory()
    ->getEditable('system.theme')
    ->set('default', 'purencool_vision')
    ->save();

  \Drupal::configFactory()
    ->getEditable('system.theme')
    ->set('admin', 'seven')
    ->save();
}
